from django.db import migrations
from django.contrib.auth.models import Group

# Generated by Django 4.2.10 on 2024-05-05 10:18

def create_groups(apps, schema_editor):
    Group.objects.create(name='admin')
    Group.objects.create(name='student')
    Group.objects.create(name='teacher')

def remove_groups(apps, schema_editor):
    Group.objects.filter(name__in=['admin', 'student', 'teacher']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]