# Generated by Django 5.0.4 on 2024-05-27 12:24

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    call_command(
        "loaddata",
        "country.json",
        app_label="userprofiles",
    )


def unload_initial_data(apps, schema_editor):
    CountryModel = apps.get_model("userprofiles", "Country")
    CountryModel.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20240527_1223'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, unload_initial_data),
    ]
