# Generated by Django 5.0.4 on 2024-06-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20240610_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
