# Generated by Django 5.0.4 on 2024-06-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20240610_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
