# Generated by Django 5.0.4 on 2024-11-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20240610_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='announcement_last_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discussion_last_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
