# Generated by Django 5.0.4 on 2024-06-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_auto_20240604_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofiles.institution'),
        ),
    ]
