# Generated by Django 5.0.4 on 2024-09-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_userprofile_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
