# Generated by Django 5.0.4 on 2024-11-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_userprofile_announcement_last_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='announcement_last_read',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='discussion_last_read',
        ),
    ]
