# Generated by Django 5.0.4 on 2024-05-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_auto_20240524_0539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['label'], 'verbose_name_plural': 'Countries'},
        ),
    ]
