server {
    listen 80;
    server_name _;

    # Serve static files from the 'static' directory
    location /_next/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /_next/$uri =404;
    }

    location /static/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
    }

    # Serve the rest of the files, e.g., images, index.html
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Handle errors
    error_page  500 502 503 504  /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
