version: "3.8"
services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app

  frontend:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - frontend/.env

volumes:
  postgres-data:
