version: "3.8"
services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    env_file:
      - backend/.env

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
