version: "3.8"
services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: django-app
    image: sanjueranga/mooc-backend:latest # Docker Compose will pull this automatically
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - backend/.env

  frontend:
    container_name: nextjs-app
    image: sanjueranga/mooc-frontend:latest 
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  postgres-data:
