services:
  postgres:
    container_name: container-pg
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moocuser -d mooc"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    restart: always
    command: >
      sh -c "python manage.py migrate &&
            gunicorn mooc.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: node-frontend
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  postgres-data:
