CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "userprofiles_authenticationtype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "label" varchar(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "userprofiles_country" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "label" varchar(100) NOT NULL UNIQUE, "country_code" varchar(5) NOT NULL);
CREATE TABLE IF NOT EXISTS "userprofiles_degree" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "label" varchar(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "userprofiles_interest" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "label" varchar(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "userprofiles_usertype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "label" varchar(100) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "userprofiles_institution" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "label" varchar(100) NOT NULL UNIQUE, "profile_picture" varchar(100) NULL, "country_id" bigint NULL REFERENCES "userprofiles_country" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "userprofiles_userprofile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "profile_picture" varchar(1000) NULL, "profile_image" varchar(100) NULL, "description" text NULL, "headline" varchar(500) NULL, "birth_date" date NULL, "mobile_number" varchar(15) NULL, "gender" varchar(1) NULL, "country_id" bigint NULL REFERENCES "userprofiles_country" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "userprofiles_userprofile_interests" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "userprofile_id" bigint NOT NULL REFERENCES "userprofiles_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED, "interest_id" bigint NOT NULL REFERENCES "userprofiles_interest" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "userprofiles_education" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "field_of_study" varchar(100) NULL, "degree" varchar(500) NOT NULL, "start_date" varchar(7) NOT NULL, "end_date" varchar(7) NULL, "institution_id" bigint NOT NULL REFERENCES "userprofiles_institution" ("id") DEFERRABLE INITIALLY DEFERRED, "user_profile_id" bigint NOT NULL REFERENCES "userprofiles_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "userprofiles_workexperience" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "company" varchar(100) NOT NULL, "position" varchar(100) NOT NULL, "start_date" varchar(7) NOT NULL, "end_date" varchar(7) NULL, "user_profile_id" bigint NOT NULL REFERENCES "userprofiles_userprofile" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "userprofiles_institution_country_id_8a319a2c" ON "userprofiles_institution" ("country_id");
CREATE INDEX "userprofiles_userprofile_country_id_088a8e8a" ON "userprofiles_userprofile" ("country_id");
CREATE UNIQUE INDEX "userprofiles_userprofile_interests_userprofile_id_interest_id_bd15bef6_uniq" ON "userprofiles_userprofile_interests" ("userprofile_id", "interest_id");
CREATE INDEX "userprofiles_userprofile_interests_userprofile_id_c8230f70" ON "userprofiles_userprofile_interests" ("userprofile_id");
CREATE INDEX "userprofiles_userprofile_interests_interest_id_f45dcdc0" ON "userprofiles_userprofile_interests" ("interest_id");
CREATE INDEX "userprofiles_education_institution_id_6a8f3ef5" ON "userprofiles_education" ("institution_id");
CREATE INDEX "userprofiles_education_user_profile_id_e87fdcde" ON "userprofiles_education" ("user_profile_id");
CREATE INDEX "userprofiles_workexperience_user_profile_id_a580fb8c" ON "userprofiles_workexperience" ("user_profile_id");
CREATE TABLE IF NOT EXISTS "courses_component" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "type" varchar(255) NULL, "chapter_id" bigint NOT NULL REFERENCES "courses_chapter" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_videoquiz" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "question" text NOT NULL, "options" text NOT NULL CHECK ((JSON_VALID("options") OR "options" IS NULL)), "correct_option" integer NOT NULL, "time_stamp" varchar(255) NULL);
CREATE TABLE IF NOT EXISTS "courses_codingassignment" ("component_ptr_id" bigint NOT NULL PRIMARY KEY REFERENCES "courses_component" ("id") DEFERRABLE INITIALLY DEFERRED, "question" text NULL, "explanation" text NULL, "grading_type" varchar(255) NULL, "duration" integer NULL, "test_cases" text NULL CHECK ((JSON_VALID("test_cases") OR "test_cases" IS NULL)), "language" varchar(255) NULL, "starter_code" text NULL);
CREATE TABLE IF NOT EXISTS "courses_note" ("component_ptr_id" bigint NOT NULL PRIMARY KEY REFERENCES "courses_component" ("id") DEFERRABLE INITIALLY DEFERRED, "content" text NULL);
CREATE TABLE IF NOT EXISTS "courses_quiz" ("component_ptr_id" bigint NOT NULL PRIMARY KEY REFERENCES "courses_component" ("id") DEFERRABLE INITIALLY DEFERRED, "deadline" datetime NULL, "duration" bigint NULL);
CREATE TABLE IF NOT EXISTS "courses_video" ("component_ptr_id" bigint NOT NULL PRIMARY KEY REFERENCES "courses_component" ("id") DEFERRABLE INITIALLY DEFERRED, "video_id" varchar(255) NULL, "video_link" varchar(1000) NULL, "duration" varchar(255) NULL, "quizzes" text NULL CHECK ((JSON_VALID("quizzes") OR "quizzes" IS NULL)));
CREATE TABLE IF NOT EXISTS "courses_announcement" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "content" text NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_itemchat" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "message" text NOT NULL, "created_at" datetime NOT NULL, "visibility" varchar(10) NOT NULL, "component_id" bigint NOT NULL REFERENCES "courses_component" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_message" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "visibility" varchar(10) NOT NULL, "time" datetime NOT NULL, "content" text NOT NULL, "course_id" bigint NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_answer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "text" varchar(255) NOT NULL, "is_correct" bool NOT NULL, "question_id" bigint NOT NULL REFERENCES "courses_question" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_reply" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "time" datetime NOT NULL, "content" text NOT NULL, "message_id" bigint NOT NULL REFERENCES "courses_message" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_threadmessage" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "message" text NOT NULL, "created_at" datetime NOT NULL, "chat_id" bigint NOT NULL REFERENCES "courses_itemchat" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_week" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_chapter" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "week_id" bigint NOT NULL REFERENCES "courses_week" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "courses_component_chapter_id_338f98f4" ON "courses_component" ("chapter_id");
CREATE INDEX "courses_announcement_user_id_772864e7" ON "courses_announcement" ("user_id");
CREATE INDEX "courses_announcement_course_id_2fd5ffea" ON "courses_announcement" ("course_id");
CREATE INDEX "courses_itemchat_component_id_d3a92fb1" ON "courses_itemchat" ("component_id");
CREATE INDEX "courses_itemchat_user_id_9c5b8732" ON "courses_itemchat" ("user_id");
CREATE INDEX "courses_message_course_id_4d3377f9" ON "courses_message" ("course_id");
CREATE INDEX "courses_message_user_id_d05207a2" ON "courses_message" ("user_id");
CREATE INDEX "courses_answer_question_id_f7e35d1f" ON "courses_answer" ("question_id");
CREATE INDEX "courses_reply_message_id_4047368b" ON "courses_reply" ("message_id");
CREATE INDEX "courses_reply_user_id_178ca613" ON "courses_reply" ("user_id");
CREATE INDEX "courses_threadmessage_chat_id_fbfcf5d9" ON "courses_threadmessage" ("chat_id");
CREATE INDEX "courses_threadmessage_user_id_5bf31c9a" ON "courses_threadmessage" ("user_id");
CREATE UNIQUE INDEX "courses_week_name_course_id_9cc78ba3_uniq" ON "courses_week" ("name", "course_id");
CREATE INDEX "courses_week_course_id_ff2e0576" ON "courses_week" ("course_id");
CREATE INDEX "courses_chapter_week_id_8e21983d" ON "courses_chapter" ("week_id");
CREATE TABLE IF NOT EXISTS "courses_image" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "image" varchar(100) NOT NULL, "note_id" bigint NOT NULL REFERENCES "courses_note" ("component_ptr_id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "courses_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "score" integer NOT NULL, "text" text NOT NULL, "question_type" varchar(2) NOT NULL, "quiz_id" bigint NOT NULL REFERENCES "courses_quiz" ("component_ptr_id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "courses_image_note_id_a81165c6" ON "courses_image" ("note_id");
CREATE INDEX "courses_question_quiz_id_7bd87b34" ON "courses_question" ("quiz_id");
CREATE TABLE IF NOT EXISTS "courses_progress" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "completed" bool NOT NULL, "component_id" bigint NOT NULL REFERENCES "courses_component" ("id") DEFERRABLE INITIALLY DEFERRED, "enrollment_id" bigint NOT NULL REFERENCES "courses_enrollment" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "courses_progress_enrollment_id_component_id_31df57bc_uniq" ON "courses_progress" ("enrollment_id", "component_id");
CREATE INDEX "courses_progress_component_id_14d1608c" ON "courses_progress" ("component_id");
CREATE INDEX "courses_progress_enrollment_id_23314a24" ON "courses_progress" ("enrollment_id");
CREATE TABLE IF NOT EXISTS "coursemanagement_coursepermissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "label" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "coursemanagement_courseteachers_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "courseteachers_id" bigint NOT NULL REFERENCES "coursemanagement_courseteachers" ("id") DEFERRABLE INITIALLY DEFERRED, "coursepermissions_id" bigint NOT NULL REFERENCES "coursemanagement_coursepermissions" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "coursemanagement_courseteachers_permissions_courseteachers_id_coursepermissions_id_15bba458_uniq" ON "coursemanagement_courseteachers_permissions" ("courseteachers_id", "coursepermissions_id");
CREATE INDEX "coursemanagement_courseteachers_permissions_courseteachers_id_bda4f0c8" ON "coursemanagement_courseteachers_permissions" ("courseteachers_id");
CREATE INDEX "coursemanagement_courseteachers_permissions_coursepermissions_id_f7f0bc8a" ON "coursemanagement_courseteachers_permissions" ("coursepermissions_id");
CREATE TABLE IF NOT EXISTS "courses_lastseen" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "last_seen" datetime NOT NULL, "chat_id" bigint NOT NULL REFERENCES "courses_itemchat" ("id") DEFERRABLE INITIALLY DEFERRED, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "courses_studentlastseen_chat_id_e6c4fa57" ON "courses_lastseen" ("chat_id");
CREATE INDEX "courses_studentlastseen_course_id_d34af151" ON "courses_lastseen" ("course_id");
CREATE INDEX "courses_studentlastseen_user_id_41a39d83" ON "courses_lastseen" ("user_id");
CREATE TABLE IF NOT EXISTS "courses_lastseencourse" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "last_seen_announcement" datetime NOT NULL, "last_seen_discussion" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "courses_lastseencourse_course_id_1d503a3b" ON "courses_lastseencourse" ("course_id");
CREATE INDEX "courses_lastseencourse_user_id_73791401" ON "courses_lastseencourse" ("user_id");
CREATE TABLE IF NOT EXISTS "coursemanagement_payments" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" datetime NOT NULL, "enrollement_id" bigint NOT NULL REFERENCES "courses_enrollment" ("id") DEFERRABLE INITIALLY DEFERRED, "status" varchar(10) NOT NULL, "student_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "amount" decimal NULL, "order_id" varchar(100) NULL, "payment_id" varchar(100) NULL);
CREATE INDEX "coursemanagement_payments_enrollement_id_54181fbe" ON "coursemanagement_payments" ("enrollement_id");
CREATE INDEX "coursemanagement_payments_student_id_2cde9b87" ON "coursemanagement_payments" ("student_id");
CREATE TABLE IF NOT EXISTS "courses_studentcodinganswer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "code" text NOT NULL, "grade" decimal NOT NULL, "graded" bool NOT NULL, "enrollement_id" bigint NOT NULL REFERENCES "courses_enrollment" ("id") DEFERRABLE INITIALLY DEFERRED, "coding_assignment_id" bigint NOT NULL REFERENCES "courses_codingassignment" ("component_ptr_id") DEFERRABLE INITIALLY DEFERRED, "test_results" text NULL CHECK ((JSON_VALID("test_results") OR "test_results" IS NULL)));
CREATE INDEX "courses_studentcodinganswer_enrollement_id_19626e07" ON "courses_studentcodinganswer" ("enrollement_id");
CREATE INDEX "courses_studentcodinganswer_coding_assignment_id_bf5a0a03" ON "courses_studentcodinganswer" ("coding_assignment_id");
CREATE TABLE IF NOT EXISTS "courses_enrollment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date_enrolled" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED, "student_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "paid" bool NOT NULL, "certificate_id" varchar(255) NULL, "certificate_url" varchar(255) NULL, "completion_date" datetime NULL);
CREATE UNIQUE INDEX "courses_enrollment_course_id_student_id_46471c5a_uniq" ON "courses_enrollment" ("course_id", "student_id");
CREATE INDEX "courses_enrollment_course_id_2631503e" ON "courses_enrollment" ("course_id");
CREATE INDEX "courses_enrollment_student_id_aebf8536" ON "courses_enrollment" ("student_id");
CREATE TABLE IF NOT EXISTS "courses_course" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "description" text NULL, "specifications" text NULL, "faculty" varchar(255) NULL, "department" varchar(255) NULL, "outcomes" text NULL CHECK ((JSON_VALID("outcomes") OR "outcomes" IS NULL)), "header_image" varchar(100) NULL, "duration" varchar(255) NULL, "difficulty" varchar(255) NOT NULL, "status" varchar(255) NOT NULL, "payment_type" varchar(50) NOT NULL, "price" decimal NULL, "category_id" bigint NOT NULL REFERENCES "userprofiles_interest" ("id") DEFERRABLE INITIALLY DEFERRED, "course_creator_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "institution_id" bigint NOT NULL REFERENCES "userprofiles_institution" ("id") DEFERRABLE INITIALLY DEFERRED, "finished" bool NOT NULL, "syllabus" text NULL CHECK ((JSON_VALID("syllabus") OR "syllabus" IS NULL)));
CREATE INDEX "courses_course_category_id_d64b93bf" ON "courses_course" ("category_id");
CREATE INDEX "courses_course_course_creator_id_2f4b1cdd" ON "courses_course" ("course_creator_id");
CREATE INDEX "courses_course_institution_id_34e4044f" ON "courses_course" ("institution_id");
CREATE TABLE IF NOT EXISTS "courses_studentquiz" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "score" decimal NOT NULL, "graded" bool NOT NULL, "completed_at" datetime NOT NULL, "student_answers" text NOT NULL CHECK ((JSON_VALID("student_answers") OR "student_answers" IS NULL)), "enrollement_id" bigint NOT NULL REFERENCES "courses_enrollment" ("id") DEFERRABLE INITIALLY DEFERRED, "quiz_id" bigint NOT NULL REFERENCES "courses_quiz" ("component_ptr_id") DEFERRABLE INITIALLY DEFERRED, "grade_approved" bool NOT NULL);
CREATE INDEX "courses_studentquiz_enrollement_id_195ed25e" ON "courses_studentquiz" ("enrollement_id");
CREATE INDEX "courses_studentquiz_quiz_id_b605f2fd" ON "courses_studentquiz" ("quiz_id");
CREATE TABLE IF NOT EXISTS "coursemanagement_courseteachers" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "role" varchar(20) NOT NULL, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED, "teacher_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "messages" text NULL CHECK ((JSON_VALID("messages") OR "messages" IS NULL)));
CREATE UNIQUE INDEX "coursemanagement_courseteachers_course_id_teacher_id_003ac63f_uniq" ON "coursemanagement_courseteachers" ("course_id", "teacher_id");
CREATE INDEX "coursemanagement_courseteachers_course_id_80731f83" ON "coursemanagement_courseteachers" ("course_id");
CREATE INDEX "coursemanagement_courseteachers_teacher_id_0e47050f" ON "coursemanagement_courseteachers" ("teacher_id");
CREATE TABLE IF NOT EXISTS "coursemanagement_adminmessages" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "message" text NOT NULL, "date" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED, "sender" varchar(10) NOT NULL);
CREATE INDEX "coursemanagement_adminmessages_course_id_3f7925a4" ON "coursemanagement_adminmessages" ("course_id");
CREATE TABLE IF NOT EXISTS "courses_videofile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "hls_playlist" varchar(100) NULL, "hls_segments" text NULL CHECK ((JSON_VALID("hls_segments") OR "hls_segments" IS NULL)), "file" varchar(100) NULL);
