# Generated by Django 5.0.4 on 2024-06-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseManagment',
            new_name='CourseManagement',
        ),
    ]
