# Generated by Django 5.0.4 on 2024-09-19 08:20

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    call_command(
        "loaddata",
        "permissions.json",
        app_label="coursemanagement",
    )


def unload_initial_data(apps, schema_editor):
    CoursePermissions = apps.get_model("coursemanagement", "CoursePermissions")
    CoursePermissions.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("coursemanagement", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_data, unload_initial_data),
    ]
