# Generated by Django 5.0.4 on 2024-09-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteachers',
            name='role',
            field=models.CharField(choices=[('editing_teacher', 'Editing Teacher'), ('non-editing_teacher', 'Non-Editing Teacher')], default='non-editing_teacher', max_length=20),
        ),
    ]
