# Generated by Django 5.0.4 on 2024-11-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0002_auto_20241109_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteachers',
            name='messages',
            field=models.JSONField(default=dict),
        ),
    ]
