# Generated by Django 5.0.4 on 2024-12-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0003_courseteachers_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteachers',
            name='messages',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
