# Generated by Django 5.0.4 on 2024-06-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0003_assignment_course_enrollment_instructor_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
