# Generated by Django 5.0.4 on 2024-12-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0004_alter_courseteachers_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessages',
            name='sender',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
