# Generated by Django 5.0.4 on 2024-11-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0004_payments_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='user',
            new_name='student',
        ),
    ]
