# Generated by Django 5.0.4 on 2024-06-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0004_alter_course_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructor',
            new_name='CourseTeachers',
        ),
    ]
