# Generated by Django 5.0.4 on 2024-06-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0005_rename_instructor_courseteachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTeachers',
            new_name='CourseTeacher',
        ),
    ]
