# Generated by Django 5.0.4 on 2024-11-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0006_alter_payments_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
