# Generated by Django 5.0.4 on 2024-11-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
