# Generated by Django 5.0.4 on 2024-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
