# Generated by Django 5.0.4 on 2024-07-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('name', 'course')},
        ),
    ]
