# Generated by Django 5.0.4 on 2024-06-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
