# Generated by Django 5.0.4 on 2024-07-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SC', 'Single Correct'), ('MC', 'Multiple Correct'), ('OE', 'Open Ended')], max_length=2),
        ),
    ]
