# Generated by Django 5.0.4 on 2024-06-03 10:38
from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from courses.models import (
    Course,
    Week,
    Chapter,
    Component,
    Note,
    Quiz,
    Image,
    Question,
    Answer,
    Video,
    CodingAssignment,
    Progress,
    UserAnswer,
    UserCodingAnswer,
)


def assign_permissions(apps, schema_editor):
    # Define the models for which you want to assign permissions
    admin_teacher_models = [
        Course,
        Week,
        Chapter,
        Component,
        Note,
        Quiz,
        Video,
        CodingAssignment,
        Image,
        Question,
        Answer,
    ]
    student_models = [Progress, UserAnswer, UserCodingAnswer]

    # Get the groups
    admin = Group.objects.get(name="admin")
    teacher = Group.objects.get(name="teacher")
    student = Group.objects.get(name="student")

    for model in admin_teacher_models:
        # Get the permissions for the model
        content_type = ContentType.objects.get_for_model(model)
        permissions = Permission.objects.filter(content_type=content_type)

        # Assign the permissions to the admin and teacher groups
        for permission in permissions:
            admin.permissions.add(permission)
            teacher.permissions.add(permission)

    for model in student_models:
        # Get the permissions for the model
        content_type = ContentType.objects.get_for_model(model)
        permissions = Permission.objects.filter(content_type=content_type)

        # Assign the permissions to the student group
        for permission in permissions:
            student.permissions.add(permission)


def remove_permissions(apps, schema_editor):
    # Define the models for which you want to remove permissions
    admin_teacher_models = [
        Course,
        Chapter,
        Component,
        Note,
        Quiz,
        Video,
        CodingAssignment,
    ]
    student_models = [Progress, UserAnswer, UserCodingAnswer]

    # Get the groups
    admin = Group.objects.get(name="admin")
    teacher = Group.objects.get(name="teacher")
    student = Group.objects.get(name="student")

    for model in admin_teacher_models:
        # Get the permissions for the model
        content_type = ContentType.objects.get_for_model(model)
        permissions = Permission.objects.filter(content_type=content_type)

        # Remove the permissions from the admin and teacher groups
        for permission in permissions:
            admin.permissions.remove(permission)
            teacher.permissions.remove(permission)

    for model in student_models:
        # Get the permissions for the model
        content_type = ContentType.objects.get_for_model(model)
        permissions = Permission.objects.filter(content_type=content_type)

        # Remove the permissions from the student group
        for permission in permissions:
            student.permissions.remove(permission)


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(assign_permissions, remove_permissions),
    ]
