# Generated by Django 5.0.4 on 2024-07-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_component_component_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='component_type',
            new_name='type',
        ),
    ]
