# Generated by Django 5.0.4 on 2024-07-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_chapter_week_alter_component_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
    ]
