# Generated by Django 5.0.4 on 2024-11-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
