# Generated by Django 5.0.4 on 2024-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_option', models.IntegerField()),
                ('time_stamp', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='quizzes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('enrollment', 'component')},
        ),
    ]
