# Generated by Django 5.0.4 on 2025-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_videofile_hls_playlist_videofile_hls_segments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quiz_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SC', 'Single Correct'), ('MC', 'Multiple Correct'), ('OE', 'Open Ended'), ('FU', 'File Upload')], max_length=2),
        ),
    ]
