# Generated by Django 5.0.4 on 2024-11-12 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_studentlastseen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentLastSeen',
            new_name='LastSeen',
        ),
    ]
