# Generated by Django 5.0.4 on 2025-05-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_uploadedfile_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
