# Generated by Django 5.0.4 on 2024-11-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment_certificate_id_enrollment_certificate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
