# Generated by Django 5.0.4 on 2024-09-28 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_videoquiz_video_quizzes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingassignment',
            name='deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='codingassignment',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
