# Generated by Django 5.0.4 on 2024-07-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
