# Generated by Django 5.0.4 on 2024-09-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_codingassignment_deadline_codingassignment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingassignment',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
