# Generated by Django 5.0.4 on 2024-11-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
