# Generated by Django 5.0.4 on 2024-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquiz',
            name='grade_approved',
            field=models.BooleanField(default=False),
        ),
    ]
