# Generated by Django 5.0.4 on 2024-07-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_video_video_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoFile',
        ),
    ]
