# Generated by Django 5.0.4 on 2024-11-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_price'),
        ('courses', '0005_studentcodinganswer_test_results'),
    ]

    operations = [
    ]
