# Generated by Django 5.0.4 on 2024-09-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_codingassignment_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingassignment',
            name='grading_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
