# Generated by Django 5.0.4 on 2024-11-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_merge_20241116_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquiz',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
