# Generated by Django 5.0.4 on 2025-01-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_studentquiz_grade_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls/'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='hls_segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
