# Generated by Django 5.0.4 on 2024-09-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_codingassignment_grading_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquiz',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
