# Generated by Django 5.0.4 on 2024-11-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_studentquiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
