# Generated by Django 5.0.4 on 2024-09-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_studentquiz_graded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='full_grades',
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
