# Generated by Django 5.0.4 on 2024-09-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_quiz_full_grades_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='payment_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Completely Paid'), ('trial', '1 Week Free Trial and Paid')], default='trial', max_length=50),
        ),
    ]
