# Generated by Django 5.0.4 on 2024-07-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_video_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='video',
        ),
    ]
