# Generated by Django 5.0.4 on 2025-01-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_videofile_file_alter_videofile_hls_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='file',
        ),
    ]
