# Generated by Django 5.0.4 on 2024-10-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_department_course_faculty_course_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingassignment',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
