# Generated by Django 5.0.4 on 2024-10-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_codingassignment_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingassignment',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
