# Generated by Django 5.0.4 on 2025-01-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_videofile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
