# Generated by Django 5.0.4 on 2024-07-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
