# Generated by Django 5.0.4 on 2024-10-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_codingassignment_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingassignment',
            name='starter_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
