# Generated by Django 5.0.4 on 2024-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_codingassignment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingassignment',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
