# Generated by Django 5.0.4 on 2024-10-07 06:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_message_discussion_message_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread',
            new_name='Reply',
        ),
    ]
