# Generated by Django 5.0.4 on 2024-10-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_rename_thread_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='visibility',
        ),
    ]
