# Generated by Django 5.0.4 on 2024-10-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_reply_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='video',
            name='chat',
        ),
    ]
