# Generated by Django 5.0.4 on 2024-10-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_note_chat_remove_video_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemChat',
        ),
    ]
