# Generated by Django 5.0.4 on 2024-10-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_itemchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='visibility',
            field=models.CharField(choices=[('all', 'All'), ('teachers', 'Teachers')], default='all', max_length=10),
        ),
    ]
