# Generated by Django 5.0.4 on 2024-11-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_threadmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcodinganswer',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
