name: Deploy

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no github-user@$SERVER_IP 'echo "SSH connection successful!"'
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
