name: Deploy

on:
  push:
    branches:
      - development

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t sanjueranga/mooc-backend:latest -f Dockerfile.backend .
          docker build -t sanjueranga/mooc-frontend:latest -f Dockerfile.frontend .

      - name: Push Docker images
        run: |
          docker push sanjueranga/mooc-backend:latest
          docker push sanjueranga/mooc-frontend:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SECRET }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -p 222 github-user@$SERVER_IP 'bash /mooc/deploy.sh'
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
